[tool.poetry]
name = "nebula"
version = "6.0.0-rc.1"
description = "Open source broadcast automation system"
authors = ["Nebula Broadcast <info@nebulabroadcast.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "^22.1.0"
asyncpg = "^0.27.0"
fastapi = "^0.92"
httpx = "^0.23.3"
mistune = "^2.0.4"
nxtools = "^1.6"
orjson = "^3.8.6"
pydantic = "^1.10.4"
python-dotenv = "^0.19.2"
redis = "^4.5.1"
rich = "^12.0.1"
uvicorn = {extras = ["standard"], version = "6.0.0-rc.1"}

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^22.1.0"
flake8 = "^4.0.1"
mypy = "^0.941"
isort = "^5.10.1"
pytest-asyncio = "^0.20.3"

[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
