[tool.poetry]
name = "Nebula"
version = "6.0.0"
description = "Open source broadcast automation system"
authors = ["Nebula Broadcast <info@nebulabroadcast.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "^22.1.0"
asyncpg = "^0.27.0"
fastapi = "^0.88.0"
httpx = "^0.23.3"
mistune = "^2.0.4"
nxtools = "^1.6"
orjson = "^3.6.7"
pydantic = "^1.10.4"
python-dotenv = "^0.19.2"
redis = "^4.2.0rc1"
rich = "^12.0.1"
uvicorn = {extras = ["standard"], version = "^0.17.6"}

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^22.1.0"
flake8 = "^4.0.1"
mypy = "^0.941"
isort = "^5.10.1"

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.20.3"

[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
