name: Publish docker image

on:
  push:
    # TODO: change to main when Nebula 6 is released
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the server image
      run: docker build . --file Dockerfile --tag nebulabroadcast/nebula-server:latest

    - name: Push the server image
      run: docker push nebulabroadcast/nebula-server:latest
