name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: mltframework/mlt
        path: mlt
    
    - name: Build mlt
      run: |
        cmake .
        cmake --build .
        cmake --install .
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
